# This is a basic workflow that is manually triggered

name: Manual workflow
on:
  push:
jobs:
  # This workflow contains a single job called "greet"
  rename:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - uses: actions/checkout@v2
    - run: git mv myrepo_new ${GITHUB_REPOSITORY##*/}
    - uses: EndBug/add-and-commit@v5.1.0
