# This is a basic workflow that is manually triggered
on: [push]

jobs:
  rename:
    name: Rename repository
    runs-on: ubuntu-latest
    steps:
    #- run: git clone https://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@github.com/cicd-cs/myrepo.git
    - run: |
        pwd
        ls -la
    #- run: git mv mayrepo-new ${GITHUB_REPOSITORY##*/}
    #- run: git commit -a -m "Renoemado diretório com sucesso"
    #- run: git push
    #- uses: EndBug/add-and-commit@v5.1.0
